### PR TITLE
Mention NVIM_TUI_ENABLE_CURSOR_SHAPE

### PR DESCRIPTION
**Pull request by Pyrohh**
Hello sir, I'm from the Neovim advocacy group.

### CODE REVIEW

**Comment by mhinz** [comment]
Neovim advocacy is welcome! But not there. :->

I try to concentrate on Vim in the main text (since it's long enough already), but I'll add an extra section purely about Neovim.

In fact I'll start with it right now and I'm sure you can contribute lots of goodies there. :-)

**Comment by mhinz** [comment]
:arrow_right:  https://github.com/mhinz/vim-galore/blob/master/content/neovim.md

**Comment by Pyrohh** [comment]
> Neovim advocacy is welcome! But not there. :->

You insult my heritage :smirk: 

> In fact I'll start with it right now and I'm sure you can contribute lots of goodies there. :-)

new PR incoming.

**Comment by Pyrohh** [comment]
Oh, and thanks for starting off that section; should make it easier for Neovim users that want to contribute :D

**Pull request closed without merging**
