### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by meain**
Correct a broken link

### CODE REVIEW

**Comment by mhinz** [comment]
This is already fixed on master. Most probably you forgot to the pull latest changes. :-)

**Comment by meain** [comment]
Something is weird here, the link is still the old one even when checking README in the browser. Also when I checked with git blame the last commit to that line is at `4f9f9e76`

**Comment by mhinz** [comment]
`git pull https://github.com/mhinz/vim-galore` is giving you `Already up-to-date.`?

**Comment by meain** [comment]
Yup

**Comment by mhinz** [comment]
Are you sure you're on the master branch?

**Comment by meain** [comment]
Yup, I am on master branch. Moreover I the link seems to be broken even when checking from the browser.

**Comment by meain** [comment]
```
diff --git a/README.md b/README.md
index 9504a5f..31bf055 100644
--- a/README.md
+++ b/README.md
@@ -7,7 +7,7 @@
 ---

 Ask me anything on [Twitter](https://twitter.com/_mhinz_).
-My [vimrc](https://github.com/mhinz/dotfiles/blob/master/.vim/vimrc).
+My [vimrc](https://github.com/mhinz/dotfiles/blob/master/vim/vimrc).

 ---
```


This is how the diff is showing up for me for the commit that made the change. It actully removed .vim and added vim.

**Comment by mhinz** [comment]
I'm terribly sorry for closing this. Apparently I didn't have enough coffee yet. I missed that you fix a completely different line.

My bad!

Thanks for the contribution. ;-)

**Comment by meain** [comment]
Cool ;)

**Comment by mhinz** [comment]
I added a link reference, so that such a misunderstanding shouldn't happen again. ;-)

**Pull request merged**
