### PR TITLE
README: Update typo fix

### PR DESCRIPTION
**Pull request by staranjeet**
This PR fixes some of the typos in readme.

### CODE REVIEW

**Comment by mhinz** [comment]
Hilarious: https://github.com/staranjeet/vim-galore/commit/940dc647a200262fde18f99d9b8317fbd8aee835#diff-04c6e90faac2675aa89e2176d2eec7d8L2358

Thanks a bunch for these corrections. (I guess it's time to set up automatic checks for wrong grammar and bad markdown practices.)

**Comment by staranjeet** [comment]
Yeah, some hook can be added.
Btw, how is that my PR is closed, still I am seeing a commit 
`staranjeet committted with mhinz Typo`

**Comment by mhinz** [comment]
If often copy titles from `README.md` to `CHANGELOG.md`. Since you found 2 typos in the titles, I [amended](https://www.atlassian.com/git/tutorials/rewriting-history/git-commit--amend) them to your commit. This basically creates a new commit with a new commit hash, which is different from the hash of the commit from the PR and so Github won't recognize it as mergend and I have to close it manually.

That's the reason why you should always create new branches for PRs. Otherwise, if the PR is based on master and upstream (me) commits a modified commit, you'll have a merge conflict on the next `git pull`. (I hope this is not the case.)

**Comment by staranjeet** [comment]
I have created a new branch `typo-fix` and next time while pulling from upstream, I could have rebased. That way my master would have remain in sync with upstream. Anyways I get it that you have modified my commit message, hence the commit hash was changed. :)

**Pull request closed without merging**
